version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::732499942675:user/aws-sam-cli-managed-dev-lin-pipeline-PipelineUser-1EPLQZDKHC4EH"

[dev-lin]
[dev-lin.pipeline_bootstrap]
[dev-lin.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::732499942675:role/aws-sam-cli-managed-dev-lin-PipelineExecutionRole-1INXKA9Q754TL"
cloudformation_execution_role = "arn:aws:iam::732499942675:role/aws-sam-cli-managed-dev-l-CloudFormationExecutionR-1RA4CJ4698TBJ"
artifacts_bucket = "aws-sam-cli-managed-dev-lin-pipel-artifactsbucket-g4fpi5hf4dq1"
image_repository = ""
region = "us-east-1"

[prod-lin]
[prod-lin.pipeline_bootstrap]
[prod-lin.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::732499942675:role/aws-sam-cli-managed-prod-lin-PipelineExecutionRole-DZTBP778E115"
cloudformation_execution_role = "arn:aws:iam::732499942675:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-Z46GE2UU8HUZ"
artifacts_bucket = "aws-sam-cli-managed-prod-lin-pipe-artifactsbucket-xkp4nw3zm7tb"
image_repository = ""
region = "us-east-1"
