version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::746606725297:user/aws-sam-cli-managed-dev-lin-pipeline-PipelineUser-1UCYBK6PR69Z7"

[dev-lin]
[dev-lin.pipeline_bootstrap]
[dev-lin.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::746606725297:role/aws-sam-cli-managed-dev-lin-PipelineExecutionRole-1BD2BM2JF9SK0"
cloudformation_execution_role = "arn:aws:iam::746606725297:role/aws-sam-cli-managed-dev-l-CloudFormationExecutionR-1VA150EFNY5BR"
artifacts_bucket = "aws-sam-cli-managed-dev-lin-pipel-artifactsbucket-16dnol9triyhn"
image_repository = ""
region = "us-east-1"

[prod-lin]
[prod-lin.pipeline_bootstrap]
[prod-lin.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::746606725297:role/aws-sam-cli-managed-prod-lin-PipelineExecutionRole-11G5W7UDL640O"
cloudformation_execution_role = "arn:aws:iam::746606725297:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-XGR8KBCP3FKK"
artifacts_bucket = "aws-sam-cli-managed-prod-lin-pipe-artifactsbucket-5b9nnzmhmu3t"
image_repository = ""
region = "us-east-1"
